version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: contactdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:123456@db/contactdb
    ports:
      - "8000:8000"
